name: Continuos Integration

on:
    pull_request:
        branches: [main]
jobs:
    test_client:
      name: Test client
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./client
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
              node-version: 18.16.0
        - name: Install dependencies
          run: npm install
        - name: Run tests
          run: npm run test:ci
    test_server:
      name: Test server
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./server
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
              node-version: 18.16.0
        - name: Install dependencies
          run: npm install
        - name: Run tests
          run: npm run test:ci