name: Visualize
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Run repo-visualizer
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "./.github/images/diagram.svg"
          excluded_paths: "ignore,.github,LICENSE,.gitignore,"
<<<<<<< HEAD
          excluded_globs: "**/*.{png,ico,md,svg};**/package-lock.json;**/package.json;**/public;/images;**/tsconfig.json"
          excluded_file_names: "README"
=======
          excluded_globs: "**/*.{png,ico,md,svg};**/package-lock.json;**/package.json;**/public;/images;**/tsconfig.json"
>>>>>>> fd2278f (Fixed visualize)
